package cli

import (
	"sort"

	"github.com/KoukeNeko/taiga-cli/internal/taiga"
	buildversion "github.com/KoukeNeko/taiga-cli/internal/version"
)

const jsonSchemaDraft = "https://json-schema.org/draft/2020-12/schema"

type Safety string
type Idempotency string

const (
	SafetyRead    Safety      = "read"
	SafetyWrite   Safety      = "write"
	SafetyLocal   Safety      = "local"
	Idempotent    Idempotency = "idempotent"
	NonIdempotent Idempotency = "non_idempotent"
)

type Descriptor struct {
	Command     string         `json:"command"`
	Description string         `json:"description"`
	Safety      Safety         `json:"safety"`
	Idempotency Idempotency    `json:"idempotency"`
	Input       map[string]any `json:"input_schema"`
	Output      map[string]any `json:"output_schema"`
}

func objectSchema(properties map[string]any, required ...string) map[string]any {
	schema := map[string]any{"$schema": jsonSchemaDraft, "type": "object", "properties": properties, "additionalProperties": false}
	if len(required) > 0 {
		schema["required"] = required
	}
	return schema
}

func descriptors() map[string]Descriptor {
	stringProperty := map[string]any{"type": "string"}
	integerProperty := map[string]any{"type": "integer"}
	booleanProperty := map[string]any{"type": "boolean"}
	commonOutput := objectSchema(map[string]any{"data": map[string]any{"type": "object"}, "meta": map[string]any{"type": "object"}}, "data", "meta")
	listOutput := objectSchema(map[string]any{"items": map[string]any{"type": "array"}, "page": map[string]any{"type": "object"}, "meta": map[string]any{"type": "object"}}, "items", "meta")
	return map[string]Descriptor{
		"version":                         {Command: "version", Description: "Show CLI build information", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: dataOutputOf(buildversion.Info{})},
		"doctor":                          {Command: "doctor", Description: "Diagnose a Taiga endpoint and current context", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"host": stringProperty, "api_url": stringProperty}), Output: commonOutput},
		"doctor bundle":                   {Command: "doctor bundle", Description: "Create a redacted local diagnostic bundle", Safety: SafetyLocal, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"output": stringProperty, "force": booleanProperty}, "output"), Output: commonOutput},
		"auth login":                      {Command: "auth login", Description: "Authenticate and save credentials", Safety: SafetyLocal, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"host": stringProperty, "api_url": stringProperty, "profile": stringProperty, "with_token": booleanProperty}), Output: commonOutput},
		"auth logout":                     {Command: "auth logout", Description: "Remove saved credentials", Safety: SafetyLocal, Idempotency: Idempotent, Input: objectSchema(map[string]any{"profile": stringProperty}), Output: commonOutput},
		"auth status":                     {Command: "auth status", Description: "Show current authentication status", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: commonOutput},
		"config get":                      {Command: "config get", Description: "Read a configuration value", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"key": stringProperty, "local": booleanProperty}, "key"), Output: commonOutput},
		"config set":                      {Command: "config set", Description: "Write a configuration value", Safety: SafetyLocal, Idempotency: Idempotent, Input: objectSchema(map[string]any{"key": stringProperty, "value": stringProperty, "local": booleanProperty}, "key", "value"), Output: commonOutput},
		"config list":                     {Command: "config list", Description: "List non-secret configuration", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"local": booleanProperty}), Output: commonOutput},
		"project list":                    {Command: "project list", Description: "List projects", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"page": integerProperty, "limit": integerProperty}), Output: listOutputOf(taiga.Project{})},
		"project view":                    {Command: "project view", Description: "View a project", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty}, "slug"), Output: dataOutputOf(taiga.Project{})},
		"project use":                     {Command: "project use", Description: "Select a default project", Safety: SafetyLocal, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty, "local": booleanProperty}, "slug"), Output: commonOutput},
		"project create":                  {Command: "project create", Description: "Create a project from a template", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"name": stringProperty, "description": stringProperty, "template": stringProperty, "public": booleanProperty, "dry_run": booleanProperty}, "name", "template"), Output: commonOutput},
		"project edit":                    {Command: "project edit", Description: "Edit a project", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"slug": stringProperty, "name": stringProperty, "description": stringProperty, "public": booleanProperty, "private": booleanProperty, "epics": booleanProperty, "backlog": booleanProperty, "kanban": booleanProperty, "wiki": booleanProperty, "issues": booleanProperty, "dry_run": booleanProperty}, "slug"), Output: commonOutput},
		"project export":                  {Command: "project export", Description: "Request a portable project dump", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"slug": stringProperty, "format": stringProperty, "dry_run": booleanProperty}, "slug"), Output: dataOutputOf(projectExportView{})},
		"project import":                  {Command: "project import", Description: "Create a project from a Taiga dump", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"file": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "file"), Output: dataOutputOf(projectImportView{})},
		"project archive":                 {Command: "project archive", Description: "Archive a project when supported by Taiga", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty}, "slug"), Output: commonOutput},
		"project unarchive":               {Command: "project unarchive", Description: "Unarchive a project when supported by Taiga", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty}, "slug"), Output: commonOutput},
		"project delete":                  {Command: "project delete", Description: "Request permanent project deletion", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "slug"), Output: commonOutput},
		"project like":                    {Command: "project like", Description: "Like a project", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty, "dry_run": booleanProperty}), Output: commonOutput},
		"project unlike":                  {Command: "project unlike", Description: "Remove the current user's project like", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty, "dry_run": booleanProperty}), Output: commonOutput},
		"project fans":                    {Command: "project fans", Description: "List project fans", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"slug": stringProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(taiga.User{})},
		"project transfer request":        {Command: "project transfer request", Description: "Request project ownership transfer instructions", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"dry_run": booleanProperty}), Output: commonOutput},
		"project transfer start":          {Command: "project transfer start", Description: "Start ownership transfer to an existing member", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"user": integerProperty, "reason": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "user"), Output: commonOutput},
		"project transfer validate-token": {Command: "project transfer validate-token", Description: "Validate an ownership transfer token", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"token": stringProperty, "dry_run": booleanProperty}, "token"), Output: commonOutput},
		"project transfer accept":         {Command: "project transfer accept", Description: "Accept a project ownership transfer", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"token": stringProperty, "reason": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "token"), Output: commonOutput},
		"project transfer reject":         {Command: "project transfer reject", Description: "Reject a project ownership transfer", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"token": stringProperty, "reason": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "token"), Output: commonOutput},
		"member list":                     {Command: "member list", Description: "List project memberships", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty}), Output: listOutputOf(taiga.Membership{})},
		"member add":                      {Command: "member add", Description: "Add a member or invitation", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"username": stringProperty, "role": stringProperty, "admin": booleanProperty, "invitation_text": stringProperty, "dry_run": booleanProperty}, "username", "role"), Output: commonOutput},
		"member edit":                     {Command: "member edit", Description: "Edit a project membership", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"member": stringProperty, "role": stringProperty, "admin": booleanProperty, "dry_run": booleanProperty}, "member"), Output: commonOutput},
		"member remove":                   {Command: "member remove", Description: "Remove a member or invitation", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"member": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "member"), Output: commonOutput},
		"role list":                       {Command: "role list", Description: "List project roles", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty}), Output: listOutputOf(taiga.Role{})},
		"role create":                     {Command: "role create", Description: "Create a project role", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"name": stringProperty, "permission": map[string]any{"type": "array", "items": stringProperty}, "computable": booleanProperty, "order": integerProperty, "dry_run": booleanProperty}, "name"), Output: commonOutput},
		"role edit":                       {Command: "role edit", Description: "Edit a project role", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"role": stringProperty, "name": stringProperty, "permission": map[string]any{"type": "array", "items": stringProperty}, "computable": booleanProperty, "order": integerProperty, "dry_run": booleanProperty}, "role"), Output: commonOutput},
		"role delete":                     {Command: "role delete", Description: "Delete a role and move members", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"role": stringProperty, "move_to": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "role"), Output: commonOutput},
		"webhook list":                    {Command: "webhook list", Description: "List project webhooks", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty}), Output: listOutputOf(webhookView{})},
		"webhook view":                    {Command: "webhook view", Description: "View webhook metadata", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"webhook": stringProperty}, "webhook"), Output: dataOutputOf(webhookView{})},
		"webhook create":                  {Command: "webhook create", Description: "Create a project webhook", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"name": stringProperty, "url": stringProperty, "secret": stringProperty, "dry_run": booleanProperty}, "name", "url", "secret"), Output: commonOutput},
		"webhook edit":                    {Command: "webhook edit", Description: "Edit a project webhook", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"webhook": stringProperty, "name": stringProperty, "url": stringProperty, "secret": stringProperty, "dry_run": booleanProperty}, "webhook"), Output: commonOutput},
		"webhook test":                    {Command: "webhook test", Description: "Ask Taiga to send a test webhook", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"webhook": stringProperty}, "webhook"), Output: dataOutputOf(taiga.WebhookLog{})},
		"webhook delete":                  {Command: "webhook delete", Description: "Delete a project webhook", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"webhook": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "webhook"), Output: commonOutput},
		"custom-field list":               {Command: "custom-field list", Description: "List custom field definitions", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty}, "resource"), Output: listOutputOf(taiga.CustomField{})},
		"custom-field create":             {Command: "custom-field create", Description: "Create a custom field definition", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "name": stringProperty, "description": stringProperty, "type": stringProperty, "option": map[string]any{"type": "array", "items": stringProperty}, "order": integerProperty, "dry_run": booleanProperty}, "resource", "name", "type"), Output: commonOutput},
		"custom-field edit":               {Command: "custom-field edit", Description: "Edit a custom field definition", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "field": stringProperty, "name": stringProperty, "description": stringProperty, "type": stringProperty, "option": map[string]any{"type": "array", "items": stringProperty}, "order": integerProperty, "dry_run": booleanProperty}, "resource", "field"), Output: commonOutput},
		"custom-field delete":             {Command: "custom-field delete", Description: "Delete a custom field definition", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "field": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "resource", "field"), Output: commonOutput},
		"custom-field values":             {Command: "custom-field values", Description: "View resolved custom field values", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty}, "resource", "ref"), Output: dataOutputOf(customFieldValuesView{})},
		"custom-field set":                {Command: "custom-field set", Description: "Merge custom field values with OCC", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty, "value": map[string]any{"type": "array", "items": stringProperty}, "unset": map[string]any{"type": "array", "items": stringProperty}, "base_version": integerProperty, "dry_run": booleanProperty}, "resource", "ref"), Output: dataOutputOf(customFieldValuesView{})},
		"epic list":                       {Command: "epic list", Description: "List project epics", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(epicView{})},
		"epic view":                       {Command: "epic view", Description: "View an epic", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty}, "ref"), Output: dataOutputOf(epicView{})},
		"epic create":                     {Command: "epic create", Description: "Create an epic", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"project": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "assignee": stringProperty, "color": stringProperty, "dry_run": booleanProperty}, "subject"), Output: commonOutput},
		"epic edit":                       {Command: "epic edit", Description: "Edit an epic with OCC", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "assignee": stringProperty, "color": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"epic close":                      {Command: "epic close", Description: "Move an epic to a closed status", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "status": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"epic stories":                    {Command: "epic stories", Description: "List stories linked to an epic", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty}, "ref"), Output: listOutputOf(epicStoryView{})},
		"epic link":                       {Command: "epic link", Description: "Link a Story to an epic", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "story": stringProperty, "dry_run": booleanProperty}, "ref", "story"), Output: dataOutputOf(epicStoryView{})},
		"epic unlink":                     {Command: "epic unlink", Description: "Unlink a Story from an epic", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "story": stringProperty, "dry_run": booleanProperty}, "ref", "story"), Output: commonOutput},
		"epic watch":                      {Command: "epic watch", Description: "Watch an epic", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"epic unwatch":                    {Command: "epic unwatch", Description: "Stop watching an epic", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"epic history":                    {Command: "epic history", Description: "Show epic activity and comments", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "type": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(historyView{})},
		"epic delete":                     {Command: "epic delete", Description: "Permanently delete an epic", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"epic vote":                       {Command: "epic vote", Description: "Vote for an epic", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"epic unvote":                     {Command: "epic unvote", Description: "Remove an epic vote", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"epic watchers":                   {Command: "epic watchers", Description: "List epic watchers", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"epic voters":                     {Command: "epic voters", Description: "List epic voters", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"issue list":                      {Command: "issue list", Description: "List project issues", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(issueView{})},
		"issue view":                      {Command: "issue view", Description: "View an issue", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty}, "ref"), Output: dataOutputOf(issueView{})},
		"issue create":                    {Command: "issue create", Description: "Create an issue", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"project": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "priority": stringProperty, "severity": stringProperty, "type": stringProperty, "assignee": stringProperty, "tags": map[string]any{"type": "array", "items": stringProperty}, "dry_run": booleanProperty}, "subject"), Output: commonOutput},
		"issue edit":                      {Command: "issue edit", Description: "Edit an issue with OCC", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "priority": stringProperty, "severity": stringProperty, "type": stringProperty, "assignee": stringProperty, "tags": map[string]any{"type": "array", "items": stringProperty}, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"issue close":                     {Command: "issue close", Description: "Move an issue to a closed status", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "status": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"issue assign":                    {Command: "issue assign", Description: "Assign an issue", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "to": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref", "to"), Output: commonOutput},
		"issue comment":                   {Command: "issue comment", Description: "Comment on an issue", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "body": stringProperty, "body_file": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"issue watch":                     {Command: "issue watch", Description: "Watch an issue", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"issue unwatch":                   {Command: "issue unwatch", Description: "Stop watching an issue", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"issue history":                   {Command: "issue history", Description: "Show issue activity and comments", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "type": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(historyView{})},
		"issue delete":                    {Command: "issue delete", Description: "Permanently delete an issue", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"issue vote":                      {Command: "issue vote", Description: "Vote for an issue", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"issue unvote":                    {Command: "issue unvote", Description: "Remove an issue vote", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"issue watchers":                  {Command: "issue watchers", Description: "List issue watchers", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"issue voters":                    {Command: "issue voters", Description: "List issue voters", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"story list":                      {Command: "story list", Description: "List project user stories", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty, "sprint": stringProperty, "order_by": stringProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(storyView{})},
		"story view":                      {Command: "story view", Description: "View a user story", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty}, "ref"), Output: dataOutputOf(storyView{})},
		"story create":                    {Command: "story create", Description: "Create a user story", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"project": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "sprint": stringProperty, "tags": map[string]any{"type": "array", "items": stringProperty}, "dry_run": booleanProperty}, "subject"), Output: commonOutput},
		"story edit":                      {Command: "story edit", Description: "Edit a user story with OCC", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "sprint": stringProperty, "tags": map[string]any{"type": "array", "items": stringProperty}, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"story close":                     {Command: "story close", Description: "Move a user story to a closed status", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "status": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"story move":                      {Command: "story move", Description: "Move a user story to a sprint or backlog", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "sprint": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref", "sprint"), Output: commonOutput},
		"story assign":                    {Command: "story assign", Description: "Replace user story assignees", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "to": map[string]any{"type": "array", "items": stringProperty}, "base_version": integerProperty, "dry_run": booleanProperty}, "ref", "to"), Output: commonOutput},
		"story comment":                   {Command: "story comment", Description: "Comment on a user story", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "body": stringProperty, "body_file": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"story watch":                     {Command: "story watch", Description: "Watch a user story", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"story unwatch":                   {Command: "story unwatch", Description: "Stop watching a user story", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"story history":                   {Command: "story history", Description: "Show user story activity and comments", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "type": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(historyView{})},
		"story delete":                    {Command: "story delete", Description: "Permanently delete a user story", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"story vote":                      {Command: "story vote", Description: "Vote for a user story", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"story unvote":                    {Command: "story unvote", Description: "Remove a user story vote", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"story watchers":                  {Command: "story watchers", Description: "List user story watchers", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"story voters":                    {Command: "story voters", Description: "List user story voters", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"task list":                       {Command: "task list", Description: "List project tasks", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty, "story": stringProperty, "order_by": stringProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(taskView{})},
		"task view":                       {Command: "task view", Description: "View a task", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty}, "ref"), Output: dataOutputOf(taskView{})},
		"task create":                     {Command: "task create", Description: "Create a task", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"project": stringProperty, "story": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "assignee": stringProperty, "dry_run": booleanProperty}, "subject"), Output: commonOutput},
		"task edit":                       {Command: "task edit", Description: "Edit a task with OCC", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "subject": stringProperty, "description": stringProperty, "status": stringProperty, "story": stringProperty, "assignee": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"task done":                       {Command: "task done", Description: "Move a task to a closed status", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "status": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"task reopen":                     {Command: "task reopen", Description: "Move a task to an open status", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "status": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"task assign":                     {Command: "task assign", Description: "Assign a task", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "to": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref", "to"), Output: commonOutput},
		"task unassign":                   {Command: "task unassign", Description: "Remove a task assignee", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"task move":                       {Command: "task move", Description: "Move a task to a Story, Sprint, or backlog", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "story": stringProperty, "sprint": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"task comment":                    {Command: "task comment", Description: "Comment on a task", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "body": stringProperty, "body_file": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"task watch":                      {Command: "task watch", Description: "Watch a task", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"task unwatch":                    {Command: "task unwatch", Description: "Stop watching a task", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"task history":                    {Command: "task history", Description: "Show task activity and comments", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "type": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(historyView{})},
		"task delete":                     {Command: "task delete", Description: "Permanently delete a task", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"task vote":                       {Command: "task vote", Description: "Vote for a task", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"task unvote":                     {Command: "task unvote", Description: "Remove a task vote", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(voteView{})},
		"task watchers":                   {Command: "task watchers", Description: "List task watchers", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"task voters":                     {Command: "task voters", Description: "List task voters", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"sprint list":                     {Command: "sprint list", Description: "List project sprints", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty, "state": stringProperty, "order_by": stringProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(sprintView{})},
		"sprint view":                     {Command: "sprint view", Description: "View a sprint", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"sprint": stringProperty}, "sprint"), Output: dataOutputOf(sprintView{})},
		"sprint create":                   {Command: "sprint create", Description: "Create a sprint", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"name": stringProperty, "start": stringProperty, "finish": stringProperty, "dry_run": booleanProperty}, "name", "start", "finish"), Output: commonOutput},
		"sprint edit":                     {Command: "sprint edit", Description: "Edit a sprint", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"sprint": stringProperty, "name": stringProperty, "start": stringProperty, "finish": stringProperty, "dry_run": booleanProperty}, "sprint"), Output: commonOutput},
		"sprint close":                    {Command: "sprint close", Description: "Close a sprint", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"sprint": stringProperty, "dry_run": booleanProperty}, "sprint"), Output: commonOutput},
		"sprint reopen":                   {Command: "sprint reopen", Description: "Reopen a sprint", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"sprint": stringProperty, "dry_run": booleanProperty}, "sprint"), Output: commonOutput},
		"sprint delete":                   {Command: "sprint delete", Description: "Permanently delete a sprint", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"sprint": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "sprint"), Output: commonOutput},
		"wiki list":                       {Command: "wiki list", Description: "List project wiki pages", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(wikiView{})},
		"wiki view":                       {Command: "wiki view", Description: "View a wiki page", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty}, "ref"), Output: dataOutputOf(wikiView{})},
		"wiki create":                     {Command: "wiki create", Description: "Create a wiki page", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"project": stringProperty, "slug": stringProperty, "body": stringProperty, "body_file": stringProperty, "dry_run": booleanProperty}, "slug"), Output: commonOutput},
		"wiki edit":                       {Command: "wiki edit", Description: "Edit a wiki page with OCC", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "slug": stringProperty, "body": stringProperty, "body_file": stringProperty, "base_version": integerProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"wiki delete":                     {Command: "wiki delete", Description: "Delete a wiki page", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "ref"), Output: commonOutput},
		"wiki watch":                      {Command: "wiki watch", Description: "Watch a wiki page", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"wiki unwatch":                    {Command: "wiki unwatch", Description: "Stop watching a wiki page", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "dry_run": booleanProperty}, "ref"), Output: dataOutputOf(watchView{})},
		"wiki history":                    {Command: "wiki history", Description: "Show wiki page activity and comments", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "type": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(historyView{})},
		"wiki watchers":                   {Command: "wiki watchers", Description: "List wiki page watchers", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"ref": stringProperty, "page": integerProperty, "limit": integerProperty}, "ref"), Output: listOutputOf(taiga.Participant{})},
		"comment edit":                    {Command: "comment edit", Description: "Edit a comment by history entry ID", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty, "history_id": stringProperty, "body": stringProperty, "body_file": stringProperty, "dry_run": booleanProperty}, "resource", "ref", "history_id"), Output: commonOutput},
		"comment delete":                  {Command: "comment delete", Description: "Delete a comment by history entry ID", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty, "history_id": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "resource", "ref", "history_id"), Output: commonOutput},
		"comment undelete":                {Command: "comment undelete", Description: "Restore a deleted comment", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty, "history_id": stringProperty, "dry_run": booleanProperty}, "resource", "ref", "history_id"), Output: commonOutput},
		"comment versions":                {Command: "comment versions", Description: "List saved versions of a comment", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty, "history_id": stringProperty}, "resource", "ref", "history_id"), Output: listOutputOf(taiga.CommentVersion{})},
		"wiki-link list":                  {Command: "wiki-link list", Description: "List Wiki navigation links", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"page": integerProperty, "limit": integerProperty}), Output: listOutputOf(taiga.WikiLink{})},
		"wiki-link view":                  {Command: "wiki-link view", Description: "View a Wiki navigation link", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"link": stringProperty}, "link"), Output: dataOutputOf(taiga.WikiLink{})},
		"wiki-link create":                {Command: "wiki-link create", Description: "Create a Wiki navigation link", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"title": stringProperty, "order": integerProperty, "dry_run": booleanProperty}, "title"), Output: commonOutput},
		"wiki-link edit":                  {Command: "wiki-link edit", Description: "Edit a Wiki navigation link", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"link": stringProperty, "title": stringProperty, "order": integerProperty, "dry_run": booleanProperty}, "link"), Output: commonOutput},
		"wiki-link delete":                {Command: "wiki-link delete", Description: "Delete a Wiki link while retaining its page", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"link": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "link"), Output: commonOutput},
		"metadata list":                   {Command: "metadata list", Description: "List workflow metadata", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"kind": stringProperty}, "kind"), Output: listOutputOf(taiga.WorkflowMetadata{})},
		"metadata view":                   {Command: "metadata view", Description: "View workflow metadata", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"kind": stringProperty, "metadata": stringProperty}, "kind", "metadata"), Output: dataOutputOf(taiga.WorkflowMetadata{})},
		"metadata create":                 {Command: "metadata create", Description: "Create workflow metadata", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"kind": stringProperty, "name": stringProperty, "color": stringProperty, "order": integerProperty, "closed": booleanProperty, "archived": booleanProperty, "wip_limit": integerProperty, "value": map[string]any{"type": "number"}, "dry_run": booleanProperty}, "kind", "name"), Output: commonOutput},
		"metadata edit":                   {Command: "metadata edit", Description: "Edit workflow metadata", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"kind": stringProperty, "metadata": stringProperty, "name": stringProperty, "color": stringProperty, "order": integerProperty, "closed": booleanProperty, "archived": booleanProperty, "wip_limit": integerProperty, "clear_wip_limit": booleanProperty, "value": map[string]any{"type": "number"}, "unset_value": booleanProperty, "dry_run": booleanProperty}, "kind", "metadata"), Output: commonOutput},
		"metadata delete":                 {Command: "metadata delete", Description: "Delete workflow metadata and move related items", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"kind": stringProperty, "metadata": stringProperty, "move_to": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "kind", "metadata", "move_to"), Output: commonOutput},
		"due-date list":                   {Command: "due-date list", Description: "List due-date presets", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty}, "resource"), Output: listOutputOf(taiga.DueDate{})},
		"due-date create":                 {Command: "due-date create", Description: "Create a due-date preset", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "name": stringProperty, "days": integerProperty, "order": integerProperty, "color": stringProperty, "default": booleanProperty, "dry_run": booleanProperty}, "resource", "name"), Output: commonOutput},
		"due-date edit":                   {Command: "due-date edit", Description: "Edit a due-date preset", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "preset": stringProperty, "name": stringProperty, "days": integerProperty, "order": integerProperty, "color": stringProperty, "default": booleanProperty, "dry_run": booleanProperty}, "resource", "preset"), Output: commonOutput},
		"due-date delete":                 {Command: "due-date delete", Description: "Delete a non-default due-date preset", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "preset": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "resource", "preset"), Output: commonOutput},
		"swimlane list":                   {Command: "swimlane list", Description: "List project swimlanes", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: listOutputOf(taiga.Swimlane{})},
		"swimlane create":                 {Command: "swimlane create", Description: "Create a swimlane", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"name": stringProperty, "order": integerProperty, "dry_run": booleanProperty}, "name"), Output: commonOutput},
		"swimlane edit":                   {Command: "swimlane edit", Description: "Edit a swimlane", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"swimlane": stringProperty, "name": stringProperty, "order": integerProperty, "dry_run": booleanProperty}, "swimlane"), Output: commonOutput},
		"swimlane delete":                 {Command: "swimlane delete", Description: "Delete a swimlane and optionally move stories", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"swimlane": stringProperty, "move_to": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "swimlane"), Output: commonOutput},
		"swimlane wip":                    {Command: "swimlane wip", Description: "Set or clear a swimlane column WIP limit", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"swimlane": stringProperty, "status": stringProperty, "limit": integerProperty, "clear": booleanProperty, "dry_run": booleanProperty}, "swimlane", "status"), Output: commonOutput},
		"tag list":                        {Command: "tag list", Description: "List project tags and colors", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: listOutput},
		"tag create":                      {Command: "tag create", Description: "Create a project tag", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"name": stringProperty, "color": stringProperty, "dry_run": booleanProperty}, "name"), Output: commonOutput},
		"tag edit":                        {Command: "tag edit", Description: "Rename or recolor a project tag", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"tag": stringProperty, "name": stringProperty, "color": stringProperty, "dry_run": booleanProperty}, "tag"), Output: commonOutput},
		"tag delete":                      {Command: "tag delete", Description: "Delete a tag from the project and its work items", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"tag": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "tag"), Output: commonOutput},
		"tag mix":                         {Command: "tag mix", Description: "Merge multiple tags into a target tag", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"target": stringProperty, "from": map[string]any{"type": "array", "items": stringProperty}, "dry_run": booleanProperty}, "target", "from"), Output: commonOutput},
		"search":                          {Command: "search", Description: "Search work items in a project", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"text": stringProperty, "type": stringProperty, "limit": integerProperty}, "text"), Output: listOutputOf(searchView{})},
		"timeline":                        {Command: "timeline", Description: "Show normalized cross-resource project activity", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"only_relevant": booleanProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(timelineView{})},
		"stats project":                   {Command: "stats project", Description: "Show project backlog and velocity statistics", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty}), Output: dataOutputOf(projectStatsView{})},
		"stats issues":                    {Command: "stats issues", Description: "Show issue totals, breakdowns, and trends", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty}), Output: dataOutputOf(projectIssueStatsView{})},
		"stats members":                   {Command: "stats members", Description: "Show per-member contribution counters", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"project": stringProperty}), Output: listOutputOf(memberStatsView{})},
		"stats sprint":                    {Command: "stats sprint", Description: "Show sprint completion and burndown statistics", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"sprint": stringProperty}, "sprint"), Output: dataOutputOf(sprintStatsView{})},
		"stats system":                    {Command: "stats system", Description: "Show public Taiga instance statistics", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: dataOutputOf(taiga.SystemStats{})},
		"stats discover":                  {Command: "stats discover", Description: "Show publicly discoverable project totals", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: dataOutputOf(taiga.DiscoverStats{})},
		"batch create":                    {Command: "batch create", Description: "Create one work item per non-empty input line", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "file": stringProperty, "status": stringProperty, "sprint": stringProperty, "story": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "resource", "file"), Output: listOutputOf(batchCreatedView{})},
		"batch move":                      {Command: "batch move", Description: "Move multiple work items to a Sprint", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "id": map[string]any{"type": "array", "items": integerProperty}, "sprint": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "resource", "id", "sprint"), Output: commonOutput},
		"batch reorder":                   {Command: "batch reorder", Description: "Reorder Story or Task batches", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "id": map[string]any{"type": "array", "items": integerProperty}, "order": map[string]any{"type": "array", "items": stringProperty}, "view": stringProperty, "status": stringProperty, "swimlane": stringProperty, "sprint": stringProperty, "after": integerProperty, "before": integerProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "resource", "view"), Output: commonOutput},
		"csv export":                      {Command: "csv export", Description: "Export project work items to a verified local CSV", Safety: SafetyLocal, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "output": stringProperty, "force": booleanProperty, "dry_run": booleanProperty}, "resource"), Output: commonOutput},
		"notification policy list":        {Command: "notification policy list", Description: "List current-user project notification policies", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: listOutputOf(taiga.NotifyPolicy{})},
		"notification policy create":      {Command: "notification policy create", Description: "Provision or update the selected project notification policy", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"email": stringProperty, "live": stringProperty, "web": booleanProperty, "dry_run": booleanProperty}), Output: commonOutput},
		"notification policy edit":        {Command: "notification policy edit", Description: "Edit a notification policy", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"id": integerProperty, "email": stringProperty, "live": stringProperty, "web": booleanProperty, "dry_run": booleanProperty}, "id"), Output: commonOutput},
		"notification policy delete":      {Command: "notification policy delete", Description: "Delete a notification policy", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"id": integerProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "id"), Output: commonOutput},
		"notification web list":           {Command: "notification web list", Description: "List web notifications", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"unread": booleanProperty, "page": integerProperty, "limit": integerProperty}), Output: listOutputOf(taiga.WebNotification{})},
		"notification web read":           {Command: "notification web read", Description: "Mark one or all web notifications read", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"id": integerProperty, "all": booleanProperty, "dry_run": booleanProperty}), Output: commonOutput},
		"application list":                {Command: "application list", Description: "List registered external applications", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: listOutputOf(taiga.Application{})},
		"application tokens":              {Command: "application tokens", Description: "List current-user application tokens with secrets redacted", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"application": stringProperty}), Output: listOutputOf(taiga.ApplicationToken{})},
		"application revoke":              {Command: "application revoke", Description: "Revoke an application token", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"token_id": integerProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "token_id"), Output: commonOutput},
		"storage list":                    {Command: "storage list", Description: "List current-user storage entries", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: listOutputOf(taiga.StorageEntry{})},
		"storage get":                     {Command: "storage get", Description: "Read one current-user storage entry", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"key": stringProperty}, "key"), Output: commonOutput},
		"storage set":                     {Command: "storage set", Description: "Create or replace a current-user JSON storage entry", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"key": stringProperty, "value": map[string]any{}, "dry_run": booleanProperty}, "key", "value"), Output: commonOutput},
		"storage delete":                  {Command: "storage delete", Description: "Delete a current-user storage entry", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"key": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "key"), Output: commonOutput},
		"integration providers":           {Command: "integration providers", Description: "List supported importer adapters", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{}), Output: listOutput},
		"integration call":                {Command: "integration call", Description: "Call an extensible third-party importer action", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"provider": stringProperty, "action": stringProperty, "field": map[string]any{"type": "array", "items": stringProperty}, "input": stringProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "provider", "action"), Output: commonOutput},
		"attachment list":                 {Command: "attachment list", Description: "List work item attachments", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty}, "resource", "ref"), Output: listOutputOf(taiga.Attachment{})},
		"attachment view":                 {Command: "attachment view", Description: "View attachment metadata", Safety: SafetyRead, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "id": integerProperty}, "resource", "id"), Output: dataOutputOf(taiga.Attachment{})},
		"attachment add":                  {Command: "attachment add", Description: "Upload a work item attachment", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "ref": stringProperty, "file": stringProperty, "name": stringProperty, "description": stringProperty, "deprecated": booleanProperty, "dry_run": booleanProperty}, "resource", "ref", "file"), Output: commonOutput},
		"attachment download":             {Command: "attachment download", Description: "Download and verify an attachment", Safety: SafetyLocal, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "id": integerProperty, "output": stringProperty, "force": booleanProperty, "dry_run": booleanProperty}, "resource", "id"), Output: commonOutput},
		"attachment edit":                 {Command: "attachment edit", Description: "Edit attachment metadata", Safety: SafetyWrite, Idempotency: NonIdempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "id": integerProperty, "description": stringProperty, "deprecated": booleanProperty, "dry_run": booleanProperty}, "resource", "id"), Output: commonOutput},
		"attachment delete":               {Command: "attachment delete", Description: "Delete an attachment", Safety: SafetyWrite, Idempotency: Idempotent, Input: objectSchema(map[string]any{"resource": stringProperty, "id": integerProperty, "yes": booleanProperty, "dry_run": booleanProperty}, "resource", "id"), Output: commonOutput},
	}
}

func descriptorNames(values map[string]Descriptor) []string {
	names := make([]string, 0, len(values))
	for name := range values {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
